In [40]:
"""
Created on Tue Feb 11 20:21:57 2020

@author: Chaev-Tech
"""



import random
import numpy as np
random.seed()
#mylist = [ ( random.randint(0, 100), random.randint(0, 100) ) for k in range(10) ]

grid = np.array([[0, 0, 0, 0, 0, 1],
                [1, 1, 0, 0, 0, 1],
                [0, 0, 0, 1, 0, 0],
                [0, 1, 1, 0, 0, 1],
                [0, 1, 0, 0, 1, 0],
                [0, 1, 0, 0, 0, 2]])
x_y_size = 6
solution = [[0]*sq for _ in range(x_y_size)]
#grid = [ ( random.randint(0, 1), random.randint(0, 1) ) for k in range(10) ]
#grid = np.random.randint(0,2, size=(10,10))
    
i=0
def search(x, y):
    if grid[x][y] == 2:
        print ('ВЫХОД В %d,%d' % (x, y))
        grid[x][y] = 0
        return True
    elif grid[x][y] == 1:
        print ('СТЕНА В  %d,%d' % (x, y))
        return False
    elif grid[x][y] == 0:
        global i
        i += 1
        print(i)
        print ('ПОСЕТИЛ %d,%d' % (x, y))
        return False
    
    print ('ПОСЕЩАЮ %d,%d' % (x, y))

    # set a mark as has been
    grid[x][y] = 3

    # explore neighbors clockwise starting by the one on the right
    if ((x < len(grid)-1 and search(x+1, y))
        or (y > 0 and search(x, y-1))
        or (x > 0 and search(x-1, y))
        or (y < len(grid)-1 and search(x, y+1))):
        return True
    return False

print(grid)
x = int(input('input x'))
y = int(input('input y'))
search(x, y)

def solvemaze(r, c, x_y_size, grid):
    #if destination is reached, maze is solved
    #destination is the last cell(maze[x_y_size-1][x_y_size-1])
    if (r==sq-1) and (c==x_y_size-1):
        solution[r][c] = 1;
        return True;
    #checking if we can visit in this cell or not
    #the indices of the cell must be in (0,SIZE-1)
    #and solution[r][c] == 0 is making sure that the cell is not already visited
    #maze[r][c] == 0 is making sure that the cell is not blocked
    if r>=0 and c>=0 and r<x_y_size and c<x_y_size and solution[r][c] == 0 and grid[r][c] == 0:
        #if safe to visit then visit the cell
        solution[r][c] = 1
        #going down
        if solvemaze(r+1, c, x_y_size, grid):
            return True
        #going right
        if solvemaze(r, c+1,x_y_size, grid):
            return True
        #going up
        if solvemaze(r-1, c,x_y_size, grid):
            return True
        #going left
        if solvemaze(r, c-1,x_y_size, grid):
            return True
        #backtracking
        solution[r][c] = 0;
        return False;
    return 0;


if(solvemaze(0,0, x_y_size, grid)):
    for i in solution:
        print (i)
else:
    print ("No solution")







[[0 0 0 0 0 1]
 [1 1 0 0 0 1]
 [0 0 0 1 0 0]
 [0 1 1 0 0 1]
 [0 1 0 0 1 0]
 [0 1 0 0 0 2]]


input x 0
input y 0


1
ПОСЕТИЛ 0,0
[1, 1, 1, 0, 0, 0]
[0, 0, 1, 1, 1, 0]
[0, 0, 0, 0, 1, 0]
[0, 0, 0, 1, 1, 0]
[0, 0, 0, 1, 0, 0]
[0, 0, 0, 1, 1, 1]
